name: Django Polls CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      EC2_CONNECTION_STRING: ec2-54-180-134-129.ap-northeast-2.compute.amazonaws.com
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
    - name: Run Server
      run: |
        echo "hello world"
        echo "${{ secrets.EC2_PRIVATE_SECRET }}" > my-key.pem
        chmod 400 my-key.pem
        ssh -o StrictHostKeyChecking=no -i my-key.pem ubuntu@${{ env.EC2_CONNECTION_STRING }} "bash -s" < runserver.sh