name: EC2 deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        echo "hello world"
        echo "${{ secrets.EC2_PRIVATE_SECRET }}" > my-secret.pem
        chmod 400 my-secret.pem
        ssh -o StrictHostKeyChecking=no -i my-secret.pem ubuntu@ec2-3-37-128-58.ap-northeast-2.compute.amazonaws.com '
          date > current_time.txt
        '
