name: EC2 deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        echo "hello world"
        echo "${{ secrets.EC2_PRIVATE_SECRET }}" > my-key.pem
        chmod 400 my-key.pem
        cat my-key.pem
